name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DSPACE_HOST: ${{ secrets.DSPACE_HOST }}
  DSPACE_PORT: ${{ secrets.DSPACE_PORT }}
  DSPACE_REST_HOST: ${{ secrets.DSPACE_REST_HOST }}
  DSPACE_REST_PORT: ${{ secrets.DSPACE_REST_PORT }}
  DSPACE_REST_SSL: ${{ secrets.DSPACE_REST_SSL }}
  DSPACE_SSL: ${{ secrets.DSPACE_SSL }}

jobs:
  dev:
    runs-on: [self-hosted, Linux, x64, dev]
    environment:
      name: dev
      url: "http://172.16.24.33:5000"

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "19"
      - run: |
          sh deploy.sh
