name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  REST_HOST: ${{ secrets.REST_HOST }}
  REST_PORT: ${{ secrets.REST_PORT }}

jobs:
  dev:
    runs-on: [self-hosted, Linux, x64, dev]
    environment:
      name: dev
      url: "http://172.16.24.33:5000"

    steps:
    - name: Print environment variables
      run: |
        echo "HOST: $HOST"
        echo "PORT: $PORT"
        echo "REST_HOST: $REST_HOST"
        echo "REST_PORT: $REST_PORT"

      
      - uses: actions/checkout@v3
        with:
          node-version: "19"
      - run: |
          sh deploy.sh
